#ifndef PRODUCT_H
#define PRODUCT_H

#include <stdint.h>
#include <stdlib.h>

typedef enum Product 
{
	Iron_Ore,
	Iron,
	Coal,
	Carbon,
	Carbon_Monoxide,
	Carbon_Dioxide,
	Carbonic_Acid,
	Steel,
	Copper_Ore,
	Copper,
	Copper_Wire,
	Sand,
	Silicon,
	Water,
	Heavy_Water,
	Hydrogen,
	Deuterium,
	Oxygen,
	Sulfur,
	Sulfur_Dioxide,
	Crude_Oil,
	Petroleum_Gas,
	Gasoline,
	Naptha,
	Plastic,
	Kerosene,
	Aviation_Fuel,
	Diesel,
	Fuel_Oil,
	Lubricating_Oil,
	Bitumen,
	Asphalt,
	Rock,
	Crushed_Rock,
	Lime,
	Nitrogen,
	Nitric_Oxide,
	Nitrous_Oxide,
	Nitrogen_Dioxide,
	Ammonia,
	Nitric_Acid,
	Ammonium_Nitrate,
	Urea,
	Fertiliser,
	Wheat,
	Flour,
	Bread,
	Timber,
	Lumber,
	Furniture,
	Paper,
	Tissue,
	Cotton,
	Cotton_Fabric,
	Apparel,
	Tool,
	Beef,
	Milk,
	Manure,
	Graphite,
	Lithium_Carbonate,
	Lithium_Hydroxide,
	Calcium_Hydroxide,
	Lime_Mineral,
	Lithium_Peroxide,
	Lithium_Oxide,
	Calcium_Carbonate,
	Hydrogen_Peroxide,
	Lithium_Hexafluorophosphate,
	Lithium_Battery,
	Sulfuric_Acid,
	Fluorite,
	Hydrogen_Fluoride,
	Lithium_Fluoride,
	Phosphorus_Pentachloride,
	Hydrogen_Chloride,
	Calcium_Sulfate,
	Phosphorus_Trichloride,
	Chlorine,
	Phosphorus,
	Table_Salt,
	Sodium_Hydroxide,
	Phosphorite,
	Wollastonite,
	Calcium,
	Bauxite,
	Alumina,
	Aluminum,
	PRODUCT_COUNT
} Product;

const char* getNameProduct(const Product product);
const char* getState(const Product product);
const char* getShort(const Product product);
const char* getCategory(const Product product);
const uint_fast16_t getGreenhouse(const Product product);
const float getAcidity(const Product product);


#endif