#ifndef WINDOW_TYPES_H
#define WINDOW_TYPES_H

typedef enum WindowTypes {
	FACTORY_LIST,
	FACTORY_MENU,
	LOCATION_GROUP,
	LOCATION_MENU,
	LOGISTICS_CONTRACT_MENU,
	LOGISTICS_MANAGER_LIST,
	LOGISTICS_MANAGER_MENU,
	MAIN_MENU,
	ORDER_MENU,
	PRODUCT_MARKET_LIST,
	PRODUCT_MARKET_MENU,
	SIMULATION_CONTROL_MENU,
	STOCKPILE_MENU,
	VEHICLE_MENU
} WindowTypes;

#endif