#ifndef WINDOW_TYPES_H
#define WINDOW_TYPES_H

typedef enum WindowTypes {
	FACTORY_LIST,
	FACTORY,
	LOCATION_GROUP,
	LOCATION,
	LOGISTICS_CONTRACT_MENU,
	LOGISTICS_MANAGER_LIST,
	LOGISTICS_MANAGER_MENU,
	MAIN_MENU,
	ORDER,
	PRODUCT_MARKET_LIST,
	PRODUCT_MARKET,
	STOCKPILE,
	VEHICLE,
} WindowTypes;

#endif